<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lbo_documents"
 *
 * Auto generated by Extension Builder 2014-08-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'lbo_documents',
	'description' => 'List of documents or PDFs',
	'category' => 'plugin',
	'author' => 'Manuel Bergeron',
	'author_email' => 'manuel.bergeron@libeo.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);